# Generated by Django 6.0.7 on 2026-07-08 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, help_text='Unique 7-character base62 code', max_length=10, unique=True, verbose_name='Short code')),
                ('url_original', models.TextField(help_text='The long URL to redirect to', verbose_name='Original URL')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('clicks', models.IntegerField(default=0, verbose_name='Click count')),
                ('activo', models.BooleanField(default=True, help_text='Inactive links return 410 Gone', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'db_table': 'links',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['activo'], name='idx_links_activo')],
            },
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent')),
                ('referer', models.TextField(blank=True, default='', verbose_name='Referer')),
                ('fecha_click', models.DateTimeField(auto_now_add=True, verbose_name='Clicked at')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_entries', to='links.link', verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Analytics Entry',
                'verbose_name_plural': 'Analytics Entries',
                'db_table': 'analytics',
                'ordering': ['-fecha_click'],
                'indexes': [models.Index(fields=['-fecha_click'], name='idx_analytics_fecha')],
            },
        ),
    ]
