# Generated by Django 6.0.7 on 2026-07-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='IP Address'),
        ),
    ]
